### ISSUE TITLE
Easy Drawing After Eraser

### ISSUE THREAD

**Issue by romans8** [LegendEffects/PixelBot-Designer#10]
It would be nice after clicking the eraser and erasing then choosing a color that it switched to the pencil with the color instead of having to click the pencil again to get back to drawing.

**Comment by LegendEffects** [comment]
There are keybinds implemented but I will add this as an option

Current keybinds:
- Pen (b)
- Eraser (e)
- Eyedropper (i)
- Fill (g)

**Comment by LegendEffects** [comment]
Added. #11
